### ISSUE TITLE
Make migrations table configurable

### ISSUE THREAD

**Issue by dheeth** [eugenetriguba/bolt#4]
We have a use-case where we want to run migrations from different sources but maintain different table for each source. Making the table configurable from `bolt_configurations` will resolve the issue

**Comment by eugenetriguba** [comment]
@dheeth Thanks for raising your use case 🙂 I'm not sure I 100% understand it so maybe you could help me get there.

Are you saying that you'd like to be able to use a different name than "bolt_migrations" for your migrations table? I wasn't exactly sure what is being referred to by bolt_configurations

**Comment by pawan-mehta-dt** [comment]
Yes, you are correct. Sorry I meant `bolt_migrations`. We need this table to be configurable

**Comment by eugenetriguba** [comment]
@dheeth @pawan-mehta-dt This has been released with v0.10.0 🙂
